#ifndef VERSION_UTILS_H_IN
#define VERSION_UTILS_H_IN

#define EYS3D_DEPTH_VERSION_MAJOR 1
#define EYS3D_DEPTH_VERSION_MINOR 0
#define EYS3D_DEPTH_VERSION_PATCH 0
#define EYS3D_DEPTH_VERSION_TWEAK 1

#define WRAPPER_VERSION "1.0.0.1"
#define GIT_BRANCH "master"
#define GIT_HASH "d5be8506"
#define BUILD_TIMESTAMP "2024-01-18 15:27:43"

#endif // VERSION_UTILS_H_IN
