#ifndef VERSION_UTILS_H_IN
#define VERSION_UTILS_H_IN

#define EYS3D_DEPTH_VERSION_MAJOR 1
#define EYS3D_DEPTH_VERSION_MINOR 0
#define EYS3D_DEPTH_VERSION_PATCH 0
#define EYS3D_DEPTH_VERSION_TWEAK 29

#define WRAPPER_VERSION "1.0.0.29"
#define GIT_BRANCH "sinet_dev"
#define GIT_HASH "e6d77dd1"
#define BUILD_TIMESTAMP "2021-10-21 09:12:50"

#endif // VERSION_UTILS_H_IN
