#ifndef VERSION_UTILS_H_IN
#define VERSION_UTILS_H_IN

#define EYS3D_DEPTH_VERSION_MAJOR 1
#define EYS3D_DEPTH_VERSION_MINOR 0
#define EYS3D_DEPTH_VERSION_PATCH 0
#define EYS3D_DEPTH_VERSION_TWEAK 28

#define WRAPPER_VERSION "1.0.0.28"
#define GIT_BRANCH "general_wrapper"
#define GIT_HASH "a32c2e2"
#define BUILD_TIMESTAMP "2021-09-07 13:06:43"

#endif // VERSION_UTILS_H_IN
