/*
 * Copyright (C) 2021 eYs3D Corporation
 * All rights reserved.
 * This project is licensed under the Apache License, Version 2.0.
 */

#pragma once

#ifdef WIN32
#  include "eSPDI_Common.h"
#else
#  include "eSPDI_def.h"
#endif

namespace libeYs3D    {
namespace video    {

typedef enum    {
    COLOR_RAW_DATA_YUY2 = APCImageType::COLOR_YUY2,
    COLOR_RAW_DATA_MJPG = APCImageType::COLOR_MJPG,
} COLOR_RAW_DATA_TYPE;

#define DEPTH_RAW_DATA_INTERLEAVE_MODE_OFFSET    APC_DEPTH_DATA_INTERLEAVE_MODE_OFFSET
#define DEPTH_RAW_DATA_SCALE_DOW_MODE_OFFSET    APC_DEPTH_DATA_SCALE_DOWN_MODE_OFFSET

// reference eSPDI/eSPDI_def.h
typedef enum    {
    DEPTH_RAW_DATA_OFF_RAW = APC_DEPTH_DATA_OFF_RAW,         /* raw (depth off, only raw color) */
    DEPTH_RAW_DATA_DEFAULT = APC_DEPTH_DATA_DEFAULT,         /* raw (depth off, only raw color) */
    DEPTH_RAW_DATA_8_BITS = APC_DEPTH_DATA_8_BITS,           /* rectify, 1 byte per pixel */
    DEPTH_RAW_DATA_14_BITS = APC_DEPTH_DATA_14_BITS,         /* rectify, 2 byte per pixel */
    DEPTH_RAW_DATA_8_BITS_x80 = APC_DEPTH_DATA_8_BITS_x80,   /* rectify, 2 byte per pixel but using 1 byte only */
    DEPTH_RAW_DATA_11_BITS = APC_DEPTH_DATA_11_BITS,         /* rectify, 2 byte per pixel but using 11 bit only */
    DEPTH_RAW_DATA_OFF_RECTIFY = APC_DEPTH_DATA_OFF_RECTIFY, /* rectify (depth off, only rectify color) */
    DEPTH_RAW_DATA_8_BITS_RAW = APC_DEPTH_DATA_8_BITS_RAW,         /* raw */
    DEPTH_RAW_DATA_14_BITS_RAW = APC_DEPTH_DATA_14_BITS_RAW,       /* raw */
    DEPTH_RAW_DATA_8_BITS_x80_RAW = APC_DEPTH_DATA_8_BITS_x80_RAW, /* raw */
    DEPTH_RAW_DATA_11_BITS_RAW = APC_DEPTH_DATA_11_BITS_RAW,       /* raw */
    DEPTH_RAW_DATA_14_BITS_COMBINED_RECTIFY = APC_DEPTH_DATA_14_BITS_COMBINED_RECTIFY,
    DEPTH_RAW_DATA_11_BITS_COMBINED_RECTIFY = APC_DEPTH_DATA_11_BITS_COMBINED_RECTIFY, // multi-baseline
    
    // For Interleave mode depth data type
    DEPTH_RAW_DATA_ILM_OFF_RAW = APC_DEPTH_DATA_ILM_OFF_RAW,
    DEPTH_RAW_DATA_ILM_DEFAULT = APC_DEPTH_DATA_ILM_DEFAULT,
    DEPTH_RAW_DATA_ILM_8_BITS = APC_DEPTH_DATA_ILM_8_BITS,
    DEPTH_RAW_DATA_ILM_14_BITS = APC_DEPTH_DATA_ILM_14_BITS,
    DEPTH_RAW_DATA_ILM_8_BITS_x80 = APC_DEPTH_DATA_ILM_8_BITS_x80,
    DEPTH_RAW_DATA_ILM_11_BITS = APC_DEPTH_DATA_ILM_11_BITS,
    DEPTH_RAW_DATA_ILM_OFF_RECTIFY = APC_DEPTH_DATA_ILM_OFF_RECTIFY,
    DEPTH_RAW_DATA_ILM_8_BITS_RAW = APC_DEPTH_DATA_ILM_8_BITS_RAW,
    DEPTH_RAW_DATA_ILM_14_BITS_RAW = APC_DEPTH_DATA_ILM_14_BITS_RAW,
    DEPTH_RAW_DATA_ILM_8_BITS_x80_RAW = APC_DEPTH_DATA_ILM_8_BITS_x80_RAW,
    DEPTH_RAW_DATA_ILM_11_BITS_RAW = APC_DEPTH_DATA_ILM_11_BITS_RAW,
    DEPTH_RAW_DATA_ILM_14_BITS_COMBINED_RECTIFY = APC_DEPTH_DATA_ILM_14_BITS_COMBINED_RECTIFY,
    DEPTH_RAW_DATA_ILM_11_BITS_COMBINED_RECTIFY = APC_DEPTH_DATA_ILM_11_BITS_COMBINED_RECTIFY,

    DEPTH_RAW_DATA_SCALE_DOWN_OFF_RAW = APC_DEPTH_DATA_SCALE_DOWN_OFF_RAW,
    DEPTH_RAW_DATA_SCALE_DOWN_DEFAULT = APC_DEPTH_DATA_SCALE_DOWN_DEFAULT,
    DEPTH_RAW_DATA_SCALE_DOWN_8_BITS = APC_DEPTH_DATA_SCALE_DOWN_8_BITS,
    DEPTH_RAW_DATA_SCALE_DOWN_14_BITS = APC_DEPTH_DATA_SCALE_DOWN_14_BITS,
    DEPTH_RAW_DATA_SCALE_DOWN_8_BITS_x80 = APC_DEPTH_DATA_SCALE_DOWN_8_BITS_x80,
    DEPTH_RAW_DATA_SCALE_DOWN_11_BITS = APC_DEPTH_DATA_SCALE_DOWN_11_BITS,
    DEPTH_RAW_DATA_SCALE_DOWN_OFF_RECTIFY = APC_DEPTH_DATA_SCALE_DOWN_OFF_RECTIFY,
    DEPTH_RAW_DATA_SCALE_DOWN_8_BITS_RAW = APC_DEPTH_DATA_SCALE_DOWN_8_BITS_RAW,
    DEPTH_RAW_DATA_SCALE_DOWN_14_BITS_RAW = APC_DEPTH_DATA_SCALE_DOWN_14_BITS_RAW,
    DEPTH_RAW_DATA_SCALE_DOWN_8_BITS_x80_RAW = APC_DEPTH_DATA_SCALE_DOWN_8_BITS_x80_RAW,
    DEPTH_RAW_DATA_SCALE_DOWN_11_BITS_RAW = APC_DEPTH_DATA_SCALE_DOWN_11_BITS_RAW,
    DEPTH_RAW_DATA_SCALE_DOWN_14_BITS_COMBINED_RECTIFY = APC_DEPTH_DATA_SCALE_DOWN_14_BITS_COMBINED_RECTIFY,
    DEPTH_RAW_DATA_SCALE_DOWN_11_BITS_COMBINED_RECTIFY = APC_DEPTH_DATA_SCALE_DOWN_11_BITS_COMBINED_RECTIFY,

    DEPTH_RAW_DATA_SCALE_DOWN_ILM_OFF_RAW = APC_DEPTH_DATA_SCALE_DOWN_ILM_OFF_RAW,
    DEPTH_RAW_DATA_SCALE_DOWN_ILM_DEFAULT = APC_DEPTH_DATA_SCALE_DOWN_ILM_DEFAULT,
    DEPTH_RAW_DATA_SCALE_DOWN_ILM_8_BITS = APC_DEPTH_DATA_SCALE_DOWN_ILM_8_BITS,
    DEPTH_RAW_DATA_SCALE_DOWN_ILM_14_BITS = APC_DEPTH_DATA_SCALE_DOWN_ILM_14_BITS,
    DEPTH_RAW_DATA_SCALE_DOWN_ILM_8_BITS_x80 = APC_DEPTH_DATA_SCALE_DOWN_ILM_8_BITS_x80,
    DEPTH_RAW_DATA_SCALE_DOWN_ILM_11_BITS = APC_DEPTH_DATA_SCALE_DOWN_ILM_11_BITS,
    DEPTH_RAW_DATA_SCALE_DOWN_ILM_OFF_RECTIFY = APC_DEPTH_DATA_SCALE_DOWN_ILM_OFF_RECTIFY,
    DEPTH_RAW_DATA_SCALE_DOWN_ILM_8_BITS_RAW = APC_DEPTH_DATA_SCALE_DOWN_ILM_8_BITS_RAW,
    DEPTH_RAW_DATA_SCALE_DOWN_ILM_14_BITS_RAW = APC_DEPTH_DATA_SCALE_DOWN_ILM_14_BITS_RAW,
    DEPTH_RAW_DATA_SCALE_DOWN_ILM_8_BITS_x80_RAW = APC_DEPTH_DATA_SCALE_DOWN_ILM_8_BITS_x80_RAW,
    DEPTH_RAW_DATA_SCALE_DOWN_ILM_11_BITS_RAW = APC_DEPTH_DATA_SCALE_DOWN_ILM_11_BITS_RAW,
    DEPTH_RAW_DATA_SCALE_DOWN_ILM_14_BITS_COMBINED_RECTIFY = APC_DEPTH_DATA_SCALE_DOWN_ILM_14_BITS_COMBINED_RECTIFY,
    DEPTH_RAW_DATA_SCALE_DOWN_ILM_11_BITS_COMBINED_RECTIFY = APC_DEPTH_DATA_SCALE_DOWN_ILM_11_BITS_COMBINED_RECTIFY
} DEPTH_RAW_DATA_TYPE;

} // namespace video
} // namespace libeYs3D
